### ISSUE TITLE
Add copy to clipboard button

### ISSUE THREAD

**Issue by jonblack** [cmbi/xssp-rest#20]
Add a button to make it easy for the user to copy the output to the clipboard.

**Comment by touwwouter** [comment]
Perhaps we should close this issue and open a new one 'Add save to file button'?
Most users will use ctrl-A ctrl-C anyway (even when a copy button exists)...

**Comment by jonblack** [comment]
#21 is for saving to file. I'm happy to close this since the implementation isn't trivial: javascript is blocked from accessing the keyboard, so the only method is something horrendous like flash.
