### ISSUE TITLE
Specify PDB file format requirements in help tour

### ISSUE THREAD

**Issue by touwwouter** [cmbi/xssp-rest#70]
The minimal requirements of the PDB file should be listed in the help tour. This should prevent users from uploading PDB files in a format mkdssp cannot handle and should in combination with #63 and #64 improve feedback.

Examples:
- All backbone atoms should be present (O is not used for secondary structure definition, but is necessary for calculation and output of the C=O-C=O torsion angle).
- If a SOURCE record is present, it should not be empty (cmbi/xssp#53).
- B-factors (or other values in the B-factor column) should have meaningful values if present (cmbi/xssp#54).
- Occupancy should be present (cmbi/xssp#52).

**Comment by jonblack** [comment]
@touwwouter 
Are the bullet-points above the exact text you want in the help tour?

**Comment by touwwouter** [comment]
Almost. Let's specify all text when we have decided what the format of the PDB file should be (cf. other issues in xssp and xssp-rest).

**Comment by touwwouter** [comment]
The requirements have been specified now. Start a new issue if they need to be changed.
