### ISSUE TITLE
Add contact details

### ISSUE THREAD

**Issue by touwwouter** [cmbi/xssp-rest#72]
Should users be able to contact the developers for help or feature requests? Or should the help and feedback be sufficient?

**Comment by jonblack** [comment]
It doesn't hurt to add an email address. I'd prefer this to a contact form for the following reasons:

* If it fails silently, the user doesn't know and assumes the email has been received;
* The user never knows if they'll get a copy of the email;
* It's less work to add an email address.

The downside to an email address is of course spam from bots that parse the email address.

If we add a contact form, it's obvious where it will go. If we use an email address, we need to think about where that would go.

@touwwouter 
What do you prefer?

**Comment by touwwouter** [comment]
A link to http://swift.cmbi.ru.nl/gv/facilities/ might also suffice. We'll discuss this soon.
